# apiVersion: kafka.strimzi.io/v1beta2
# kind: Kafka
# metadata:
#   name: my-cluster
# spec:
#   kafka:
#     version: 3.1.0
#     replicas: 1
#     listeners:
#       # Read "Accessing Kafka outside of the Kubernetes cluster":
#       # https://strimzi.io/docs/operators/latest/configuring.html#assembly-accessing-kafka-outside-cluster-str
#       - name: external
#         port: 9094
#         type: nodeport
#         tls: false
#       - name: plain
#         port: 9092
#         type: internal
#         tls: false
#       - name: tls
#         port: 9093
#         type: internal
#         tls: true
#     config:
#       offsets.topic.replication.factor: 1
#       transaction.state.log.replication.factor: 1
#       transaction.state.log.min.isr: 1
#       default.replication.factor: 1
#       min.insync.replicas: 1
#       inter.broker.protocol.version: "3.1"
#     storage:
#       type: ephemeral
#   zookeeper:
#     replicas: 3
#     storage:
#       type: ephemeral
#   entityOperator:
#     topicOperator: {}
#     userOperator: {}


apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    version: 3.1.0
    replicas: 1
    listeners:
      # Read "Accessing Kafka outside of the Kubernetes cluster":
      # https://strimzi.io/docs/operators/latest/configuring.html#assembly-accessing-kafka-outside-cluster-str
      - name: external
        port: 9094
        type: nodeport
        tls: false
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.1"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 5Gi
        class: local-path
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 5Gi
      class: local-path
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}